# Site settings
title: Dhaval Purohit
description: 'Rubyist | Full Stack Developer | Football Lover'
url: https://dhavalpurohit.com
baseurl: /
google_analytics: 'UA-73294222-2'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Dhaval Purohit'
  email: dhaval.purohit08@gmail.com
  facebook_username: dhaval.purohit.92
  github_username:  dhaval0894
  linkedin_username:  dhaval-purohit-63226237

collections:
  projects:
    output: true
    permalink: /:collection/:title/
  experiences:
    output: true
    permalink: /:collection/:title/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems:
  - octopress-debugger
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
